version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: Europe/London
    cooldown:
      default-days: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "Europe/London"
    cooldown:
      default-days: 5
